### ISSUE TITLE
Error while rendering

### ISSUE THREAD

**Issue by wutti90** [jiupinjia/stylized-neural-painting#10]
Hi,

Your project really looks stunning and I want to try it out on google colab. This is the code i run:

!python /content/stylized-neural-painting/demo_prog.py \
--img_path /content/stylized-neural-painting/test_images/apple.jpg \
--canvas_color 'white' \
--canvas_size 512 \
--max_m_strokes 500 \
--max_divide 5 \
--with_ot_loss \
--renderer "oilpaintbrush" \
--renderer_checkpoint_dir "checkpoints_G_oilpaintbrush_light" \
--net_G "zou-fusion-net-light" \
--disable_preview

This is the error i get back. I do not know enough programming to fix it myself.

rendering canvas...
Traceback (most recent call last):
  File "/content/stylized-neural-painting/demo_prog.py", line 113, in <module>
    optimize_x(pt)
  File "/content/stylized-neural-painting/demo_prog.py", line 102, in optimize_x
    CANVAS_tmp = pt._render(PARAMS, save_jpgs=False, save_video=False)
  File "/content/stylized-neural-painting/painter.py", line 137, in _render
    self.rderr.draw_stroke()
  File "/content/stylized-neural-painting/renderer.py", line 148, in draw_stroke
    return self._draw_oilpaintbrush()
  File "/content/stylized-neural-painting/renderer.py", line 326, in _draw_oilpaintbrush
    x0, y0, w, h, theta, R0, G0, B0, R2, G2, B2)
  File "/content/stylized-neural-painting/utils.py", line 286, in create_transformed_brush
    brush_alpha = (brush_alpha > 0).astype(np.float32)
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Thanks for your help!

**Comment by jiupinjia** [comment]
Hi @wutti90, thanks for your feedback. It seems that your brush texture files haven't been correctly loaded. 
Can you try `cd /content/stylized-neural-painting` first and then run `!python ./demo_prog.py` directly from the repo directory?

**Comment by wutti90** [comment]
Hello jui,

thank you for your help. I just was in the wrong directory! Now its working fine. The results are very nice. Even cleaner than through a multires neural style transfer due to the vector approach (I would assume, no expert by far). I really have to try it out with the neural style transfer which comes with it.

Thanks and have a nice day :)

**Comment by jiupinjia** [comment]
Cheers! @wutti90
