### ISSUE TITLE
Run without NVIDIA Driver?

### ISSUE THREAD

**Issue by ultramyslixs** [jiupinjia/stylized-neural-painting#12]
Would there be any way to run the program without a NVIDIA Driver and NVIDIA GPU?

**Comment by jiupinjia** [comment]
Hi @ultramyslixs, thanks for your question. We strongly recommend running on a GPU machine since the computation would be heavy for CPUs. But anyway, I will be fixing this problem and make it compatible with a CPU machine tonight. I will let you know when it's ready to use.

**Comment by ultramyslixs** [comment]
Ok, thank you!

**Comment by jiupinjia** [comment]
Hi @ultramyslixs, PyTorch-CPU mode is now supported! You can try out on your local machine without any GPU cards. But please note that you still need PyTorch installed if you run on CPU mode. You can simply follow the instructions in the README file and the code will automatically detect whether there will be any GPU cards available. If there is no GPU, the code will run on the CPU automaticlly.

**Comment by ultramyslixs** [comment]
Thanks! Running this program currently and it looks really good! Is there any way to maximize the image while the image is being generated? At the moment the image is about 1 inch wide and 1 inch long.

**Comment by jiupinjia** [comment]
Hi @ultramyslixs, I have made a minor update on the adjustable display window size. You can try again and adjust the window size as you want.

**Comment by ultramyslixs** [comment]
thank you so much!
