### ISSUE TITLE
Help runnig in CPU

### ISSUE THREAD

**Issue by sirciro** [jiupinjia/stylized-neural-painting#13]
(SNP2) C:\Users\Administrator\Nova pasta\SNP>python demo_prog.py --img_path ./test_images/1.jpg --canvas_color 'white' --max_m_strokes 500 --max_divide 5 --renderer oilpaintbrush --renderer_checkpoint_dir checkpoints_G_oilpaintbrush --net_G zou-fusion-net --disable_preview
Traceback (most recent call last):
  File "demo_prog.py", line 4, in <module>
    torch.cuda.current_device()
  File "C:\ProgramData\Anaconda3\envs\SNP2\lib\site-packages\torch\cuda\__init__.py", line 366, in current_device
    _lazy_init()
  File "C:\ProgramData\Anaconda3\envs\SNP2\lib\site-packages\torch\cuda\__init__.py", line 166, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by jiupinjia** [comment]
Hi @sirciro, thanks for your feedback. Currently, the code can only run on a GPU machine. I will be fixing this problem tonight and make it compatible with a CPU machine. I will let you know when it's ready to use.

**Comment by jiupinjia** [comment]
Hi @sirciro, PyTorch-CPU mode is now supported! You can try out on your local machine without any GPU cards. But please note that you still need PyTorch installed if you run on CPU mode. You can simply follow the instructions in the README file and the code will automatically detect whether there will be any GPU cards available. If there is no GPU, the code will run on the CPU automatically. Please let me know if there is any problem. Thanks!

**Comment by sirciro** [comment]
Yes Yes now works perfectly, congratulations on your great work

and thanks for sharing with us.
