### ISSUE TITLE
Assertion failed error

### ISSUE THREAD

**Issue by Weej1** [jiupinjia/stylized-neural-painting#15]
Hi @jiupinjia 

I am using Google Colab to run your light versions (specifically oilpaintbrush light) and everything ran fine till today - ~now I get an error like so~ disregard this thing about the error, Im an idiot, it was because I had not copied the source file into the correct directory. 

Input: 
`!python3 demo_prog.py --img_path ./test_images/papa2.jpg --canvas_color 'black' --max_m_strokes 1280 --max_divide 8 --renderer oilpaintbrush --renderer_checkpoint_dir checkpoints_G_oilpaintbrush_light --net_G zou-fusion-net-light`

edit: This was originally an error report because I got something about OpenCV assertion failed. Turns out it was because I had not copied the source file properly into the colab folder. Just putting this in here for transparency.

**Comment by jiupinjia** [comment]
You are good! Sometimes that also happens to me. Congratulations on your successful run! @Weej1

**Comment by Weej1** [comment]
Am dumb didn't copy file into the folder. Will raise another ticket for a different question.
