### ISSUE TITLE
Can you share the paramater of the husky dog?

### ISSUE THREAD

**Issue by vba34520** [jiupinjia/stylized-neural-painting#18]
Can you share the paramater of the husky dog?

<img src="https://user-images.githubusercontent.com/40198281/101304455-3ec28380-387b-11eb-96f3-ff158634c574.jpg" style="zoom:30%">

Thanks, Looking forward to your reply!

**Comment by jiupinjia** [comment]
Hi @vba34520, sorry for the late response. You can try:
`python demo_prog.py --img_path ./test_images/dog.jpg --canvas_color 'white' --max_m_strokes 500 --max_divide 5 --renderer oilpaintbrush --renderer_checkpoint_dir checkpoints_G_oilpaintbrush --net_G zou-fusion-net`
![dog_input](https://user-images.githubusercontent.com/51430557/101827616-8a389400-3afe-11eb-8e7f-031e9a45656f.png)
![dog_final_progressive](https://user-images.githubusercontent.com/51430557/101827618-8b69c100-3afe-11eb-94f4-accdac1fe9c7.png)

**Comment by vba34520** [comment]
Thank you so much!
Best wishes.
