### ISSUE TITLE
Color block drifts

### ISSUE THREAD

**Issue by Crosser1902** [jiupinjia/stylized-neural-painting#30]
After a piece of color block is drawn, it always drift in a little range.
Is there any way to fix the drawn color block and make it never move?

**Comment by jiupinjia** [comment]
Hi @Crosser1902, thanks for your question. The animation with those twisted strokes you mentioned was only for preview during the rendering process. If you like to see your final video result, you can check out your './output' folder for the MP4 file.

**Comment by Crosser1902** [comment]
@jiupinjia Thanks for replying！
