### ISSUE TITLE
Just a little suggestion

### ISSUE THREAD

**Issue by Crosser1902** [jiupinjia/stylized-neural-painting#31]
Is that technically possible that makes every stroke filled with only one single color？
I think it’s excellent for human to imitate and learn which would make this project more valuable.

Since I have not read the code yet, please forgive me for my whimsical dumb idea if it‘s totally impracticable.

**Comment by jiupinjia** [comment]
@Crosser1902 Generating time-lapse for human imitation is definitely a great and inspiring idea! Whether is it possible to fill in each stroke with a single color - technically, I would say yes, but that will require some updates on the source code. Hope that in the near future I will add this feature. Thanks!

**Comment by Crosser1902** [comment]
Expecting!
