### ISSUE TITLE
how can i run this program on GPU?

### ISSUE THREAD

**Issue by boboqazqaz** [jiupinjia/stylized-neural-painting#37]
My GPU is gtx1070.
Can I run this program on GPU? 
When I run this program. 
The CPU is 100%   but  GPU only 5%，and also rendering is very slowly
Is that right？

**Comment by jiupinjia** [comment]
Hi @boboqazqaz, thanks for your feedback, it seems you were not using your GPU. Did you install Pytorch-GPU and Cuda correctly?

**Comment by boboqazqaz** [comment]
IT seems my cudatoolkit isn't right,
My GPU driver is 462.30  ，CUDAdrier is 11.2
but i use “conda install”  just  can install  cudatoolkit  10.2
I have to install cudatoolkit  11.2？
