### ISSUE TITLE
Style Transfer Colab Notebook error

### ISSUE THREAD

**Issue by metaphorz** [jiupinjia/stylized-neural-painting#50]
The first part of the image-to-painting-nst.ipynb works fine since this is creating a painting 
through brush strokes and then a video.

The second part is the style transfer code, and I am getting an error here:
<img width="1318" alt="Screen Shot 2021-12-12 at 4 57 40 PM" src="https://user-images.githubusercontent.com/3519631/145733087-1573938d-d716-4156-aa54-235bf9a42207.png">

**Comment by jiupinjia** [comment]
Hi @metaphorz, thanks for your feedback. It seems your style image isn't loaded correctly. Did you check your `arg.style_img_path` before loading it?

**Comment by metaphorz** [comment]
You are right. I had a mistake in the style file spec.
