### ISSUE TITLE
Error with Notebook

### ISSUE THREAD

**Issue by Zumbalamambo** [jiupinjia/stylized-neural-painting#8]
It throws the following error,

```
initialize network with normal
pre-trained renderer does not exist...
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-11-a13d7e15e5e1> in <module>()
      1 pt = Painter(args=args)
----> 2 optimize_x(pt)

1 frames
/content/stylized-neural-painting/painter.py in _load_checkpoint(self)
     74         else:
     75             print('pre-trained renderer does not exist...')
---> 76             exit()
     77 
     78 

NameError: name 'exit' is not defined
```

**Comment by jiupinjia** [comment]
Hi @Zumbalamambo, are u running on Colab or on your local machine with command? It seems that the checkpoint loader cannot find your pretrained model. Have you downloaded and unzip the pretrained renderers first? If you are running locally, can you show me which command are you using?

**Comment by cucohhh** [comment]
I have the same problems, and use the command 
"python demo_prog.py --img_path ./test_images/apple.jpg --canvas_color 'white' --max_m_strokes 500 --max_divide 5 --renderer oilpaintbrush --renderer_checkpoint_dir checkpoints_G_oilpaintbrush --net_G zou-fusion-net"

I have downloaded and unzip the checkpoints_G_oilpaintbrush_light.zip, 
I want run it on my own machine, may I use some other packages or command?

**Comment by jiupinjia** [comment]
Hi @cucohhh, did you unzip the checkpoint zip file to the right place? You can try to move the zip file to your repo folder first before unzipping them. Please let me know whether this helps.

**Comment by MorganRO8** [comment]
I had the same issue, make a copy of the notebook in drive, I just totally forgot.

**Comment by amrzv** [comment]
Having the same Error in colab [notebook](https://colab.research.google.com/drive/1ch_41GtcQNQT1NLOA21vQJ_rQOjjv9D8).
```
NameError: name 'exit' is not defined
```
because `!unzip checkpoints_G_oilpaintbrush.zip` fails
```
Archive:  checkpoints_G_oilpaintbrush.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of checkpoints_G_oilpaintbrush.zip or
        checkpoints_G_oilpaintbrush.zip.zip, and cannot find checkpoints_G_oilpaintbrush.zip.ZIP, period.
```
