### ISSUE TITLE
No GPU

### ISSUE THREAD

**Issue by dfaghani** [jiupinjia/stylized-neural-painting#9]
Hi,

Thanks indeed for your work.
I wanted to run a quick test on one of our virtual machines and got stuck as there is no GPU on the VM.
Is there a way I can run it without a GPU?

Many tanks in deed!
DF

**Comment by jiupinjia** [comment]
Hi @dfaghani, thanks for your feedback. I strongly recommend running on a GPU machine since the computation would be heavy for CPUs. But anyway, I will be fixing this problem and make it compatible with a CPU machine tonight. I will let you know when it's ready to use.

**Comment by jiupinjia** [comment]
Hi @dfaghani, PyTorch-CPU mode is now supported! You can try out on your local machine without any GPU cards. But please note that you still need PyTorch installed if you run on CPU mode. You can simply follow the instructions in the README file and the code will automatically detect whether there will be any GPU cards available. If there is no GPU, the code will run on the CPU automatically. Please let me know if there is any problem. Thanks!

**Comment by dfaghani** [comment]
Hwllo,

Thank you for your quick response. 
I am still getting error messages. 
Will try to sort it out but might revert for more help!

Thank you again,
Best,
DF

**Comment by jiupinjia** [comment]
Hi @dfaghani, maybe you can post your error code here if you like. Me and other people are willing to help you.

**Comment by dfaghani** [comment]
Thank you for your support!
Here is the error message.
Upfront thanks.
DF

(base) Y:\8000-Publique\DF_Publique\PYTHON\stylized-neural-painting>python demo_prog.py --img_path ./test_images/apple.jpg --canvas_color 'white' --max_m_strokes 500 --max_divide 5 --renderer oilpaintbrush --renderer_checkpoint_dir checkpoints_G_oilpaintbrush --net_G zou-fusion-net
C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
initialize network with normal
pre-trained renderer does not exist...

**Comment by jiupinjia** [comment]
Hi @dfaghani, it seems your pre-trained renderer can't be found. Have you downloaded those pre-trained models from Google Drive and unzip them to your repo folder?

**Comment by dfaghani** [comment]
Hi,
You are absolutely right!
When I pulled the cpu version, I forgot to copy the renderers.
Many thanks!
It is running. 
Eager to see the result :-)

Kind regards and keep going!
Best,
DF

**Comment by jiupinjia** [comment]
@dfaghani haha, that happens! Congratulations!
